### ISSUE TITLE
K úvaze: Pořadí instancí v seznamu

### ISSUE THREAD

**Issue by matejdivecky** [zoul/mastodon-cz#8]
Bylo by fajn promyslet řazení instancí, buď jednoduše podle uživatelů/abecedy, nebo s nějakou mírou náhodnosti abychom předešli přetěžování instance na prvním místě a podpořili decentralizaci.

**Comment by zoul** [comment]
Též mě to napadlo. Za mě ideálně asi náhodně, ale v rámci dvou kategorií (viz #9). Mrknu na to náhodné řazení.

**Comment by zoul** [comment]
Teď se to náhodně nalosuje při každém překladu webu, to mně zatím přijde OK?

**Comment by matejdivecky** [comment]
Myslím že prozatím úplně, když se ale bude dělat design, mohli bychom je točit v javascripti při každém načtení aby to nebylo závislé na rebuildu. 
Není to ale zároveň určitě nijak kritická funkce:)
